# Generated by Django 4.0.5 on 2022-08-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.TextField(default='0000 or *000-00')),
                ('actual_size', models.TextField(default='0.0"x 0.0"', null=True)),
                ('instructions', models.TextField(null=True)),
                ('google_drive_image_urls', models.TextField(default='https://drive.google.com/file/d/1A5wF1HnsLlBA7G5zJQSZO0s8vRlgxttZ/view?usp=sharing')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='0000 or *000-00', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('toOil', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('highPriority', models.BooleanField(default=False)),
                ('partNumber', models.CharField(default='0000 or *000-00', max_length=20)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
