# Generated by Django 4.0.6 on 2022-07-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='part_no',
            field=models.TextField(default='0000 or *000-00'),
        ),
    ]
