# Generated by Django 4.0.5 on 2022-08-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_discarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
