# Generated by Django 4.0.5 on 2022-07-22 05:56

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_todo_description_todo_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.TextField(default='0000 or *000-00')),
                ('actual_size', models.TextField(default='0.0"x 0.0"')),
                ('instructions', jsonfield.fields.JSONField()),
                ('google_drive_image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='https://drive.google.com/file/d/1A5wF1HnsLlBA7G5zJQSZO0s8vRlgxttZ/view?usp=sharing'), size=None)),
            ],
        ),
    ]
