# Generated by Django 4.0.5 on 2022-07-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filterbible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterbible',
            name='instructions',
        ),
    ]
