# Generated by Django 4.0.5 on 2022-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_filterbible_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterbible',
            name='google_drive_image_urls',
        ),
        migrations.AlterField(
            model_name='filterbible',
            name='actual_size',
            field=models.TextField(default='0.0"x 0.0"', null=True),
        ),
    ]
