# Generated by Django 4.0.5 on 2022-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_filterbible_google_drive_image_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterbible',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
