# Generated by Django 4.0.5 on 2022-07-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_todo_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='part_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filterbible'),
        ),
    ]
