# Generated by Django 4.0.5 on 2022-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_todo_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='part_no',
            field=models.CharField(default='0000 or *000-00', max_length=20),
        ),
    ]
