# Generated by Django 4.0.5 on 2022-07-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_todo_part_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterbible',
            name='google_drive_image_urls',
            field=models.TextField(default='https://drive.google.com/file/d/1A5wF1HnsLlBA7G5zJQSZO0s8vRlgxttZ/view?usp=sharing'),
        ),
    ]
