# Generated by Django 4.0.5 on 2022-07-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_filterbible_google_drive_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
