# Generated by Django 4.0.5 on 2022-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_todo_completed_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
    ]
