# Generated by Django 4.0.5 on 2022-07-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_todo_high_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='0000 or *000-00', max_length=120),
        ),
    ]
