# Generated by Django 4.0.5 on 2022-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='oil',
            field=models.BooleanField(default=False),
        ),
    ]
